update jenkinsfile/Jenkinsfile.update_jenkins_specified_jobs

diff --git a/jenkinsfile/Jenkinsfile.update_jenkins_specified_jobs b/jenkinsfile/Jenkinsfile.update_jenkins_specified_jobs
--- a/jenkinsfile/Jenkinsfile.update_jenkins_specified_jobs
+++ b/jenkinsfile/Jenkinsfile.update_jenkins_specified_jobs
@@ -19,6 +19,8 @@ def update_shell="jenkins-jobs --conf /root/jenkins_jobs.ini update --workers 5"
 
 def ignore_templates="/templates/"
 
+def error_yaml_file=""
+
 pipeline {
 	agent {
         label node
@@ -85,7 +87,10 @@ pipeline {
                                     file.each{ j ->
                                         out = sh(script: "echo ${j} | grep ${ignore_templates}  && echo -n 'true' || echo -n 'false' ", returnStdout: true)
                                         if ( out == "false" ) {
-                                            sh "ls $j && ${update_shell} $j" 
+                                            out = sh(script: "ls $j && ${update_shell} $j  && echo -n 'true' || echo -n 'false' ", returnStdout: true)
+                                            if ( out == "false" ) {
+                                                error_yaml_file=error_yaml_file+'<>'+j
+                                            }
                                         }
                                     }
                                 }
@@ -93,7 +98,10 @@ pipeline {
                                     out = sh(script: "[ -f ${i} ]  && echo -n 'true' || echo -n 'false' ", returnStdout: true)
                                     echo "${i} is file: ${out}"
                                     if ( out == "true" ) {
-                                        sh "ls $i && ${update_shell} $i" 
+                                        out = sh(script: "ls $i && ${update_shell} $i  && echo -n 'true' || echo -n 'false' ", returnStdout: true)
+                                        if ( out == "false" ) {
+                                            error_yaml_file=error_yaml_file+'<>'+j
+                                        }
                                     }
                                     else {
                                         echo "${i} cannot find"
@@ -102,6 +110,17 @@ pipeline {
                                 }
                             }
                         }
+                    }
+                }
+            }
+        }
+
+        stage('check error_yaml_file'){
+            steps{
+                script{
+                    if ( error_yaml_file != '' ){
+                        echo "${error_yaml_file}"
+                        sh 'false'
                     }
                 }
             }
