update jenkinsfile/Jenkinsfile.update_jenkins_specified_jobs for DOPS-31775

diff --git a/jenkinsfile/Jenkinsfile.update_jenkins_specified_jobs b/jenkinsfile/Jenkinsfile.update_jenkins_specified_jobs
--- a/jenkinsfile/Jenkinsfile.update_jenkins_specified_jobs
+++ b/jenkinsfile/Jenkinsfile.update_jenkins_specified_jobs
@@ -8,11 +8,6 @@ if (env.git_base_url){
     git_base_url=env.git_base_url
 }
 
-def DINGTALK_TOKEN = 'c809dcef2819cae9f4baa46c46d4e4c9864af899ae81b7145987d026cc51a87a'
-if (env.DINGTALK_TOKEN){
-   DINGTALK_TOKEN = env.DINGTALK_TOKEN
-}
-
 if (!env.on_k8s){
     env.on_k8s="False"
 }
@@ -20,15 +15,11 @@ if (env.set_on_k8s) {
     env.on_k8s=env.set_on_k8s
 }
 
-def update_shell="jenkins-jobs --conf jenkins_jobs.ini update"
+def update_shell="jenkins-jobs --conf ${jenkins_jobs_ini_config} update --workers 5"
 
 pipeline {
 	agent {
-        docker {
-            label node
-            image "harbor.qianfan123.com/base/jenkins-job-builder:0.1.0"
-            args '-v ${WORKSPACE}/jenkins:/root/jenkins -v $WORKSPACE/jenkins_11_34.ini:/root/jenkins_jobs.ini'
-        }
+        label node
     }
 
     options {
@@ -39,47 +30,65 @@ pipeline {
         stage('delete workspace') {
             steps{
                 deleteDir()
-                sh 'printenv'
             }
         }
 
         stage('download Jenkins job project yaml file') {
             steps{
-				script {
-                    checkout(
-                        [$class: 'GitSCM', branches: [[name: "*/${env.GIT_BRANCH}"]],userRemoteConfigs: [[credentialsId: 'qianfan',url: "${git_base_url}/${git_project}.git"]]]
-                    )
+                script {
+                    git branch: "${env.GIT_BRANCH}", credentialsId: '17643215-09f8-4a9a-b0ea-c8e49777ce1d', url: "${git_base_url}/${git_project}.git"
+                    sh 'git submodule update --init --recursive'
+                    sh 'git submodule foreach "git pull origin master"'
+                }
+            }
+        }
+
+        stage('get git upload changed file'){
+            steps{
+                script{
+                    if ( currentBuild.changeSets != [] ) {
+                        def path=''
+                        for (changeLogSet in currentBuild.changeSets) {
+                            for (entry in changeLogSet.getItems()) {
+                                for (file in entry.getAffectedFiles()) {
+                                    if (path == ''){
+                                        path=file.getPath()
+                                    } else {
+                                        path=path+','+file.getPath()
+                                    }
+                                }
+                            }
+                        }
+                        cfgname=path
+                    }
                 }
             }
         }
 
         stage('build job'){
             steps{
-				script {
-                    echo "cfgname is: ${cfgname}"
-                    if (cfgname == 'all'){
-                        file=sh(returnStdout: true, script: 'find jenkins/')
-                        for ( String j : file ){
-                            sh "ls $j"
-                        }
-                    }
-                    else {
+                script {
+                    withDockerContainer(args: "-v ${WORKSPACE}/jenkins:/root/jenkins -v ${WORKSPACE}/${jenkins_jobs_ini_config}:/root/jenkins_jobs.ini", image: "harbor.qianfan123.com/base/jenkins-job-builder:0.1.0") {
+                        echo "cfgname is: ${cfgname}"
                         String[] cfgstr = cfgname.split(',')
                         for ( String i : cfgstr ){
-                            out = sh(script: "[ -d ${i} ]  && echo 'true' || echo 'false' ", returnStdout: true)
+                            out = sh(script: "[ -d ${i} ]  && echo -n 'true' || echo -n 'false' ", returnStdout: true)
+                            echo "${i} is dir: ${out}"
                             if ( out == "true" ) {
-                                file=sh(returnStdout: true, script: 'find ${i}')
-                                for ( String j : file ){
-                                    sh "ls $j"
+                                file=sh(returnStdout: true, script: "find ${i} -type f").split('\n')
+                                file.each{ j ->
+                                    sh "ls $j "
                                 }
                             }
                             else {
-                                out = sh(script: "[ -f ${i} ]  && echo 'true' || echo 'false' ", returnStdout: true)
+                                out = sh(script: "[ -f ${i} ]  && echo -n 'true' || echo -n 'false' ", returnStdout: true)
+                                echo "${i} is file: ${out}"
                                 if ( out == "true" ) {
-                                    sh "ls $i" 
+                                    sh "ls $i && ${update_shell} $i" 
                                 }
                                 else {
-                                    echo "${i} cannot find" 
+                                    echo "${i} cannot find"
+                                    sh "false" 
                                 }
                             }
                         }
